- core/test/test_finance.py
- devops/compose/docker-compose.yml
- devops/docker_build/README.md
- documentation/general/email.md
- helpers/lib_tasks.py
- helpers/s3.py
- helpers/send_email.py
- helpers/telegram_notify/config.py
- helpers/test/test_lib_tasks.py
- helpers/test/test_s3.py
- helpers/unit_test.py
- im/ib/connect/tasks.py
- im/ib/data/config.py
- im/ib/data/extract/ib_data_extractor.py
- im/ib/data/load/test/test_file_path_generator.py
- im/ib/metadata/extract/notebooks/Master_analyze_ib_metadata_crawler.py
- im/kibot/data/config.py
- im/kibot/metadata/config.py
- im/kibot/notebooks/kibot_data_analysis.py
- im/tasks.py
- tasks.py
- test/test_tasks.py
> Prerelease_cleanup2

- core/finance.py
- core/test/test_finance.py
> Amp task1483 fix nan bug

- dev_scripts/manage_cache.py
- dev_scripts/parallel_script_skeleton.py
- helpers/cache.py
- helpers/datetime_.py
- helpers/io_.py
- helpers/joblib_helpers.py
- helpers/printing.py
- helpers/system_interaction.py
- helpers/test/test_cache.py
- helpers/test/test_joblib_helpers.py
- helpers/timer.py
- Keep improving shared cache
- Add script to warm up cache
> Lime task20 profile and speed up loading data

- core/dataflow/nodes/sources.py
- core/dataflow/nodes/test/test_sources.py
- core/dataflow_model/master_experiment.py
- core/dataflow_model/utils.py
- core/test/test_config_utils.py
- documentation/general/git.md
- helpers/git.py
- helpers/list.py
- helpers/system_interaction.py
- helpers/test/helpers/test/test_list.py
- helpers/test/test_git.py
- helpers/test/test_lib_tasks.py
- helpers/test/test_traceback.py
- helpers/timer.py
- im/kibot/notebooks/gallery_kibot.ipynb
- im/kibot/notebooks/gallery_kibot.py
- tasks.py
Misc cosmetic changes
- Add comments
- Refactor some unit tests
> LemTask183_Implement_RH1E_02

- core/dataflow/nodes/local_level_model.py
- core/signal_processing.py
- core/statistics.py
- core/stats_computer.py
> Amp task1479 add helper function 5

- core/dataflow_source_nodes.py
- core/pandas_helpers.py
- core/test/test_dataflow_source_nodes.py
- helpers/git.py
- helpers/lib_tasks.py
- helpers/s3.py
- helpers/system_interaction.py
- helpers/test/test_s3.py
- im/ib/data/load/test/test_s3_data_loader.py
- im/ib/metadata/ib_symbols.py
- im/ib/metadata/test/test_ib_symbols.py
- im/kibot/data/load/test/test_s3_data_loader.py
- im/kibot/metadata/test/test_kibot_metadata.py
- tasks.py
- Fix issue with multiple S3 credentials
- Enable disabled unit tests
- Add invoke target to rename branch
- Fix bug in `git_create_branch`
> AmpTask1477_Break_in_GH_Actions_2021_06_15_02

- core/config/builder.py
- core/config/config_.py
- core/dataflow/builders.py
- core/dataflow/pipelines.py
- helpers/datetime_.py
- helpers/dbg.py
- helpers/test/test_s3.py
- im/kibot/metadata/load/kibot_metadata.py
- Add DUMMY token
- Remove an obsolete test
> LimeTask35_Use_a_token_DUMMY_instead_as_placeholder_for_values_in_configs

- core/config/config_.py
- core/test/test_config.py
- Improve code / unit tests for Config
- Add membership test equivalent to Dict's `key in config`
- No conceptual changes
> LimeTask30_Run_RH1E_on_tiny_universe_02

- core/backtest.py
- core/config/config_.py
- core/dataflow/core.py
- core/dataflow/nodes/sarimax_models.py
- core/dataflow_model/model_evaluator.py
- core/dataflow_model/run_experiment.py
- core/dataflow_model/utils.py
- core/dataframe_modeler.py
- core/explore.py
- core/pandas_helpers.py
- core/test/test_config.py
- core/timeseries_study.py
- dev_scripts/git/git_hooks/utils.py
- dev_scripts/notebooks/run_notebook.py
- helpers/joblib_helpers.py
- helpers/system_interaction.py
- im/ib/data/extract/gateway/unrolling_download_data_ib_loop.py
- im/ib/metadata/ib_symbols.py
- im/kibot/data/extract/download.py
- im/kibot/data/load/futures_forward_contracts.py
- im/kibot/metadata/extract/download_adjustments.py
- im/kibot/metadata/load/kibot_metadata.py
- tasks.py
- Add a description for all the `tqdm`, otherwise it's not clear what progress bars are reporting about
- Minor refactoring repeated code in Config
- Remove duplicated code from a wrong merge
> LimeTask30_Run_RH1E_on_tiny_universe_04

- core/dataflow_model/model_evaluator.py
- core/dataflow_model/model_plotter.py
> Amp task1507 streamline stats computer 3

- core/dataflow_model/model_evaluator.py
- helpers/telegram_notify/config.py
> LimeTask30_Run_RH1E_on_tiny_universe_05

- core/dataflow/nodes/transformers.py
- core/finance.py
- core/test/test_finance.py
> Amp task1534 add plumbing for offsets

- core/dataflow/runners.py
- core/dataflow/test/test_runners.py
- core/dataflow_model/master_experiment.py
- core/dataflow_model/utils.py
> Amp task1533 add rolling fit predict dag runner

- core/dataflow/runners.py
- core/dataflow_model/utils.py
Update the runner and add a hacked up loader.
> Amp task1533 add rolling fit predict dag runner 2

- core/dataflow_model/model_evaluator.py
- core/dataflow_model/notebooks/Master_model_analyzer.py
- core/dataflow_model/utils.py
> Amp task1540 visit artifacts

- core/finance.py
Resolve review #1535 comments.
> Incorporate review comments

- dev_scripts/notebooks/publish_notebook.py
- dev_scripts/notebooks/test/test_publish_notebook.py
- helpers/s3.py
> LimeTask38_Get_publish_notebook_to_work_02

- dev_scripts/notebooks/publish_notebook.py
- dev_scripts/notebooks/test/test_publish_notebook.py
- helpers/open.py
- helpers/s3.py
- Use new bucket
- Allow to open s3 notebook directly
- Update env
> LimeTask38_Get_publish_notebook_to_work_03

- core/pandas_helpers.py
- dev_scripts/client_setup/requirements.txt
- dev_scripts/git/git_hooks/pre-commit.py
- dev_scripts/git/git_hooks/utils.py
- dev_scripts/zip_files.py
- documentation/general/research_methodology.md
- helpers/printing.py
- helpers/system_interaction.py
- im/ib/data/extract/gateway/download_data_ib_loop.py
- im/ib/data/load/ib_s3_data_loader.py
- im/ib/metadata/extract/notebooks/Master_analyze_ib_metadata_crawler.py
- im/ib/metadata/ib_symbols.py
- im/kibot/data/load/kibot_s3_data_loader.py
- im/kibot/kibot_timing.md
- im/kibot/metadata/load/adjustments.py
- im/kibot/metadata/load/kibot_metadata.py
- im/kibot/metadata/load/s3_backend.py
- im/kibot/metadata/load/ticker_lists.py
- im/kibot/notebooks/kibot_data_analysis.py
- Create script that zips files in a directory maintaining the same structure
- Improve S3FS integration
- Lint and improve documentation
> LemTask228_Add_cdd_node_02

- core/dataflow_model/utils.py
Factor our subdirectory mapping.
> Amp task1505 update rb processing

- core/dataflow/nodes/sources.py
- core/pandas_helpers.py
- core/test/test_pandas_helpers.py
- dev_scripts/notebooks/publish_notebook.py
- helpers/csv_helpers.py
- helpers/s3.py
- helpers/test/test_s3.py
- im/common/metadata/symbols.py
- im/ib/data/extract/gateway/utils.py
- im/ib/data/extract/ib_data_extractor.py
- im/ib/data/load/ib_file_path_generator.py
- im/ib/data/load/ib_s3_data_loader.py
- im/kibot/data/extract/download.py
- im/kibot/metadata/load/s3_backend.py
- im/kibot/notebooks/kibot_volume_statistics.py
- Replace old boto code with s3fs
- Remove dead code
> AmpTask1549_Break_2021_07_18

- core/dataflow_model/model_evaluator.py
> Amp task1547 add data checks in evaluator stats computation

- core/finance.py
Add function to map DatetimeIndex times to epoch times.
> Amp task1557 add node to compute bar index

- core/dataflow/core.py
- core/dataflow/nodes/base.py
- core/dataflow/utils.py
- core/dataflow_model/run_experiment.py
- dev_scripts/client_setup/requirements.txt
- dev_scripts/git/git_hooks/utils.py
- dev_scripts/notebooks/publish_notebook.py
- dev_scripts/notebooks/test/test_publish_notebook.py
- dev_scripts/old/linter/linter_master_report.py
- dev_scripts/setenv_amp.sh
- devops/compose/docker-compose.yml
- documentation/technical/literature_review.md
- helpers/dbg.py
- helpers/unit_test.py
- helpers/warnings_helpers.py
- im/kibot/metadata/load/expiry_contract_mapper.py
- publish_notebooks
- Fix some bugs in publish_notebooks 
- Add a `--tag` option for adding a comment to the file of a published notebook
- Add / improve comments in the code base
- Lint
- Add discussed `get_unique_sink()` method to DAG
> AmpTask1572_Save_experiments_on_S3

- helpers/s3.py
> LimeTask87_publish_notebook_py_is_broken

- core/dataflow/visualization.py
- core/dataflow_model/run_experiment.py
- core/pandas_helpers.py
- core/plotting.py
- dev_scripts/git/git_hooks/utils.py
- dev_scripts/infra/gdrive.py
- dev_scripts/notebooks/run_notebook.py
- helpers/datetime_.py
- helpers/git.py
- helpers/hnumpy.py
- helpers/joblib_helpers.py
- helpers/lib_tasks.py
- helpers/test/test_datetime_.py
- helpers/test/test_hnumpy.py
- mypy.ini
- helpers/datetime_.py
- Add lots of useful assertions 
- helpers/hnumpy.py
- Add a context for random seed
- The rest of the files are just about fixing lints
> LmTask68_Implement_RT_interface_to_get_price_data_02

- core/dataflow/core.py
- core/dataflow/nodes/base.py
- core/dataflow/nodes/sources.py
- core/dataflow/nodes/test/test_sources.py
- core/dataflow/runners.py
- core/dataflow/test/test_real_time.py
- core/dataflow/test/test_runners.py
- core/dataflow_source_nodes.py
- core/pandas_helpers.py
- dataflow_amp/returns/pipeline.py
- dataflow_amp/returns/test/TestReturnsBuilder.test_equities1/output/test.txt
- dataflow_amp/returns/test/test_returns_pipeline.py
- `core/dataflow/nodes/sources.py`
- Add 3 types of RealTime nodes used for true real-time execution and simulation at different level of abstractions
- The rest of the PR is about:
- fixing lots of old lints
- adding architectural notes to consider for future changes
- fixing a few bugs
> LmTask68_Implement_RT_interface_to_get_price_data_04

- core/dataflow/test/test_real_time.py
- core/dataflow_source_nodes.py
- dataflow_amp/returns/pipeline.py
- dataflow_amp/returns/test/TestReturnsBuilder.test_futures1/output/test.txt
- dataflow_amp/returns/test/test_returns_pipeline.py
- helpers/printing.py
Fix break and improve some bandaids
> LmTask239_Fix_broken_lem_tests

- core/dataflow/builders.py
- core/dataflow/core.py
- core/dataflow/nodes/base.py
- core/dataflow/real_time.py
- core/dataflow/runners.py
- core/dataflow/utils.py
- core/dataflow/visitors.py
- `core/dataflow/runners.py`
- Factor out all the common code in `_AbstractDagRunner`
- The rest of the PR is cosmetic changes that unfortunately I couldn't easily break in pieces
- Introduce some types (NodeId, Method, NodeOutput, NodeState, NodeInfo) to improve the typing and clarify the code
- E.g., `Dict[str, Dict[str, Any]]` becomes `Dict[Method, NodeOutput]`
- Refresh the code to use latest convention (e.g., add docstring with imoprt, add 
- Add comments
- Fix almost all lints
- More PR needed will be needed to propagate the changes
- Since it's blocking and we've discussed these changes, I'll merge and apply review feedback later
> LmTask68_Implement_RT_interface_to_get_price_data_05

- core/dataflow/nodes/base.py
- core/dataflow/nodes/gluonts_models.py
- core/dataflow/nodes/local_level_model.py
- core/dataflow/nodes/sarimax_models.py
- core/dataflow/nodes/sklearn_models.py
- core/dataflow/nodes/sources.py
- core/dataflow/nodes/transformers.py
- core/dataflow/nodes/unsupervised_sklearn_models.py
- core/dataflow/nodes/volatility_models.py
- core/dataflow/result_bundle.py
- core/dataflow/runners.py
- core/dataflow/utils.py
- core/dataflow_source_nodes.py
- core/dataframe_modeler.py
- core/plotting.py
- helpers/datetime_.py
- im/kibot/data/load/futures_forward_contracts.py
No functional change
- A few leftovers from previous clean up
- Replace `_PANDAS_DATE_TYPE` with `hdatetime.Datetime`
- Replace `_COL_TYPE` -> `NodeColumn`
- Replace `_TO_LIST_MIXIN_TYPE` -> `NodeColumnList`
> AmpTask1619_Catch_all_issue_to_clean_core_02

- core/statistics.py
- core/test/test_statistics.py
Add a general diversity / effective count statistic.
> Amp task1623 add stable rank

- core/dataflow_model/model_plotter.py
- core/plotting.py
Add effective rank plot for correlation.
> Amp task1623 add stable rank 2

- core/finance.py
- core/signal_processing.py
Implements sign normalization and factors out usage in bets stats. The bets stats functions are well-tested and implicitly test the new function. The TODO here is to add stand-alone unit tests.
> Implement sign normalization

- core/statistics.py
> Amp task1630 add a t distribution stat

- core/dataflow_model/notebooks/Master_model_analyzer.ipynb
- core/dataflow_model/notebooks/Master_model_analyzer.py
- core/plotting.py
> Amp task1623 add stable rank 3

- core/dataflow/test/test_real_time.py
- devops/docker_build/poetry.lock
- devops/docker_build/pyproject.toml
- helpers/lib_tasks.py
Update the dev image to include `async_solipsism`
> AmpTask1637_Update_amp_image_to_add_async_solipsism

- dev_scripts/manage_cache.py
- helpers/cache.py
- helpers/cache/README.md
- helpers/joblib_helpers.py
- helpers/notebooks/cache.ipynb
- helpers/notebooks/cache.py
- helpers/s3.py
- helpers/system_interaction.py
- helpers/test/test_cache.py
- Implement prototype of S3 backend for caching layer
- Clean up and refactor the old code
> AmpTask1640_Cache_data_on_S3

- helpers/cache.py
- helpers/notebooks/cache.ipynb
- helpers/notebooks/cache.py
- im/common/data/load/abstract_data_loader.py
- im/ib/data/load/ib_s3_data_loader.py
- im/kibot/data/load/kibot_s3_data_loader.py
> AmpTask1640_Cache_data_on_S3_3

- core/backtest.py
- core/data_adapters.py
- core/dataflow/nodes/sources.py
- core/event_study/core.py
- core/explore.py
- core/finance.py
- core/pandas_helpers.py
- core/plotting.py
- core/residualizer.py
- core/statistics.py
- core/test/test_residualizer.py
- core/timeseries_study.py
- helpers/dbg.py
- helpers/hpandas.py
- im/ib/data/extract/gateway/download_data_ib_loop.py
- im/ib/data/extract/gateway/unrolling_download_data_ib_loop.py
- im/ib/data/extract/gateway/utils.py
- im/ib/data/extract/ib_data_extractor.py
- im/kibot/data/load/futures_forward_contracts.py
- im/kibot/metadata/load/kibot_metadata.py
- Implement TODO by moving functions from dbg.py to hpandas.py
- This also fixes many annoying lints
> AmpTask1619_Catch_all_issue_to_clean_core

- core/finance.py
> Amp task1685 implement more flexible resampling

- core/dataflow_model/model_evaluator.py
- core/dataflow_model/stats_computer.py
- core/dataflow_model/utils.py
- dev_scripts/jackpy
- devops/docker_scripts/run_jupyter_server.sh
- helpers/dbg.py
- helpers/introspection.py
- helpers/s3.py
- `core/dataflow_model/model_evaluator.py`
- No functional change
- Add comments, fix lints, update to latest code / comment conventions
- Factor out some common code (e.g., `_validate_series`)
- `core/dataflow_model/stats_computer.py`
- No functional change
- Add comments, fix lints, update to latest code / comment conventions
- `core/dataflow_model/utils.py`, `helpers/s3.py`
- Add support to use also local tarball of an experiment, besides an S3 one
> LimeTask146_Profile_the_experiment_notebook_02

- core/dataflow/nodes/regression_models.py
Do not use a `sample_weight_col` if `predict` is called.
> Amp task1693 fix sample weight bug

- core/dataflow/nodes/transformers.py
> Add nan_mode

- core/dataflow/nodes/test/test_transformers.py
- core/dataflow/nodes/transformers.py
Add a new (multi-level) column transformer. Add tests for this transformer and for the other multi-level column transformers.
> Amp task1714 move column arithmetic to features lib

- core/dataflow/nodes/transformers.py
> Checkpoint

- core/dataflow/nodes/test/test_transformers.py
- helpers/unit_test.py
Follow up to comments on https://github.com/alphamatic/amp/pull/1731
> Amp task1727 test transformer col renaming and na n handling 3

- core/dataflow_model/run_experiment.py
- helpers/joblib_helpers.py
- helpers/parser.py
- helpers/test/test_joblib_helpers.py
- helpers/timer.py
- Add asyncio-based parallel backend
- Fix bug in run_experiment.py that was not cleaning the dir
- Remove race-conditions from timer by avoiding a lock-less data-structure
> AmpTask1757_Parallelize_running_experiments
